name: Build and Release CUDA Package

on:
  push:
    branches:
      - main
      - master
    tags:
      - 'v*'  # Trigger on version tags

jobs:
  build-and-release:
    runs-on: ubuntu-20.04
    
    steps:
    - uses: actions/checkout@v4
    
    # Set up Python environment
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    
    # Install CUDA
    - name: Install CUDA
      uses: Jimver/cuda-toolkit@9b295696791d75d658d8de64c4a85097ad8abeaf # v0.2.16
      
    # Install system dependencies
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y freeglut3-dev libgl1-mesa-dev libglu1-mesa-dev wget curl cmake libopenblas-dev
    
    # Install MAGMA
    - name: Install MAGMA
      run: |
        sudo apt-get install -y gfortran curl
        # curl -L -o magma-2.8.0.tar.gz http://icl.utk.edu/projectsfiles/magma/downloads/magma-2.8.0.tar.gz
        # tar -xvf magma-2.8.0.tar.gz
        git clone https://github.com/icl-utk-edu/magma.git
        cd magma
        cp make.inc-examples/make.inc.openblas make.inc
        export GPU_TARGET="Maxwell Pascal Volta Turing Ampere"
        export CUDADIR=/usr/local/cuda
        export OPENBLASDIR="/usr"
        # export TORCH_CUDA_ARCH_LIST="6.0 7.0 7.5 8.0 8.6+PTX"
        make -j8
        sudo -E make install prefix=/usr/local/magma
    
    # Install Python dependencies
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install torch torchvision torchaudio
        pip install wheel setuptools build
    
    # Build the CUDA package
    - name: Build CUDA package
      run: |
        cd cuda
        TORCH_CUDA_ARCH_LIST="6.0 7.0 7.5 8.0 8.6+PTX" python setup.py bdist_wheel
    
    # Create GitHub Release if this is a tag
    - name: Create Release
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v1
      with:
        files: cuda/dist/*.whl
        generate_release_notes: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    
    # Upload wheel as artifact for branch pushes
    - name: Upload wheel artifact
      if: ${{ !startsWith(github.ref, 'refs/tags/') }}
      uses: actions/upload-artifact@v4
      with:
        name: kilonerf-cuda-wheel
        path: cuda/dist/*.whl